### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 4ourpj** [ojpifdsaew/Roblox-Creator-Hub-Theme#1]
there seem to be an error at the start
![image_2023-12-29_193910646](https://github.com/ojpifdsaew/Roblox-Creator-Hub-Theme/assets/134241013/f0b4b0bc-ac5b-4f4f-af68-b4b3dd2b4acf)

this cause it to  affect other  website as well

**Comment by ojpifdsaew** [comment]
Hi!, thanks for reporting, I have now fixed it.
